#!/bin/bash
Message="$1"
if [ "$1" = "" ]; then
	echo "Usage: $0 Commit description"
	echo ""
	echo "Now description is Add/Change file(s)".
	Message="Add/Change file(s)"
fi
cd /home/victor/Scripts/Git/Bellogrim
git add --all *
git status
git commit -m "$Message"
echo "VictorNRA 99b62c74f25fb12ce4dd0e3cf4286d2a"
git push
